# Generated by Django 5.0.7 on 2024-07-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
