# Generated by Django 5.0.7 on 2024-07-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderApp', '0003_orderproduct_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderservice',
            name='status',
            field=models.CharField(choices=[('1', 'confirmate is pending'), ('2', 'successfully'), ('3', 'canceled')], max_length=50),
        ),
    ]
